name: deploy asimov.top

on:
  push:
    branches:
      - main # 只在main分支上push触发部署
    paths-ignore: # 下列文件的变更不触发部署，可以自行添加
      - README.md
      - LICENSE

jobs:
  deploy:
    runs-on: ubuntu-latest # 使用ubuntu系统镜像运行自动化脚本

    steps: # 自动化步骤
      - name: checkout repository # 第一步，下载代码仓库
        uses: actions/checkout@v3 # 使用checkout@v3
        with:
          submodules: 'true'


      - name: rsync file to server # 第二步，rsync推文件
        uses: AEnterprise/rsync-deploy@v1.0 # 使用别人包装好的步骤镜像
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }} # 引用配置，SSH私钥
          ARGS: -avz --delete --exclude='*.pyc' # rsync参数，排除.pyc文件
          SERVER_PORT: ${{ secrets.SERVER_PORT }} # 引用配置，SSH端口
          FOLDER: ./ # 要推送的文件夹，路径相对于代码仓库的根目录
          SERVER_IP: ${{ secrets.SERVER_IP }} # 引用配置，服务器的host名（IP或者域名domain.com）
          USERNAME: ${{ secrets.USERNAME }} # 引用配置，服务器登录名
          SERVER_DESTINATION: ${{ secrets.SERVER_DESTINATION }} # 引用配置，部署到目标文件夹

      - name: hugo build # 第三步，hugo编译
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }} # 下面三个配置与上一步类似
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          # 执行远程脚本
          script: |
            hugo --minify --cleanDestinationDir
